In [3]:
import pandas as pd
df = pd.read_csv("P:\\Downloads\\House_Pricing.csv")
df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14-Oct-17,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14-Dec-17,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15-Feb-16,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14-Dec-17,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15-Feb-16,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [3]:
df.shape

(21613, 21)

In [5]:
df.columns

Index(['ID', 'Date House was Sold', 'Sale Price', 'No of Bedrooms',
       'No of Bathrooms', 'Flat Area (in Sqft)', 'Lot Area (in Sqft)',
       'No of Floors', 'Waterfront View', 'No of Times Visited',
       'Condition of the House', 'Overall Grade',
       'Area of the House from Basement (in Sqft)', 'Basement Area (in Sqft)',
       'Age of House (in Years)', 'Renovated Year', 'Zipcode', 'Latitude',
       'Longitude', 'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)'],
      dtype='object')

In [14]:
drp=["ID","Date House was Sold","Zipcode","Longitude","Latitude"]
df=df.drop(columns=drp)
df.head()

,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,Fair,7,1180.0,0,63,0,1340.0,5650
1,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,Fair,7,2170.0,400,67,1991,1690.0,7639
2,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,Fair,6,770.0,0,85,0,2720.0,8062
3,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,Excellent,7,1050.0,910,53,0,1360.0,5000
4,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,Fair,8,1680.0,0,31,0,1800.0,7503

In [15]:
df.columns

Index(['Sale Price', 'No of Bedrooms', 'No of Bathrooms',
       'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors',
       'Waterfront View', 'No of Times Visited', 'Condition of the House',
       'Overall Grade', 'Area of the House from Basement (in Sqft)',
       'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year',
       'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)'],
      dtype='object')

In [16]:
drp1=["No of Times Visited","Renovated Year","Condition of the House"]
df=df.drop(columns=drp1)
df.shape, df.head()

((21613, 13),
    Sale Price  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
 0    221900.0               3             1.00               1180.0
 1    538000.0               3             2.25               2570.0
 2    180000.0               2             1.00                770.0
 3    604000.0               4             3.00               1960.0
 4    510000.0               3             2.00               1680.0

    Lot Area (in Sqft)  No of Floors Waterfront View  Overall Grade  \
 0              5650.0           1.0              No              7
 1              7242.0           2.0              No              7
 2             10000.0           1.0              No              6
 3              5000.0           1.0              No              7
 4              8080.0           1.0              No              8

    Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
 0                                     1180.0                        0
 1                                     2170.0                      400
 2                                      770.0                        0
 3                                     1050.0                      910
 4                                     1680.0                        0

    Age of House (in Years)  Living Area after Renovation (in Sqft)  \
 0                       63                                  1340.0
 1                       67                                  1690.0
 2                       85                                  2720.0
 3                       53                                  1360.0
 4                       31                                  1800.0

    Lot Area after Renovation (in Sqft)
 0                                 5650
 1                                 7639
 2                                 8062
 3                                 5000
 4                                 7503  )

In [17]:
df.isna().sum()

Sale Price                                   4
No of Bedrooms                               0
No of Bathrooms                              4
Flat Area (in Sqft)                          9
Lot Area (in Sqft)                           9
No of Floors                                 0
Waterfront View                              0
Overall Grade                                0
Area of the House from Basement (in Sqft)    3
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Living Area after Renovation (in Sqft)       1
Lot Area after Renovation (in Sqft)          0
dtype: int64

In [18]:
df["Sale Price"].isna().sum()

np.int64(4)

In [19]:
df = df.dropna(subset=["Sale Price"])
df.isna().sum()

Sale Price                                   0
No of Bedrooms                               0
No of Bathrooms                              4
Flat Area (in Sqft)                          9
Lot Area (in Sqft)                           9
No of Floors                                 0
Waterfront View                              0
Overall Grade                                0
Area of the House from Basement (in Sqft)    3
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Living Area after Renovation (in Sqft)       1
Lot Area after Renovation (in Sqft)          0
dtype: int64

In [20]:
num_cols = df.select_dtypes(include="number").columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())
df.isna().sum()

Sale Price                                   0
No of Bedrooms                               0
No of Bathrooms                              0
Flat Area (in Sqft)                          0
Lot Area (in Sqft)                           0
No of Floors                                 0
Waterfront View                              0
Overall Grade                                0
Area of the House from Basement (in Sqft)    0
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Living Area after Renovation (in Sqft)       0
Lot Area after Renovation (in Sqft)          0
dtype: int64

In [25]:
drp2 = ["Waterfront View"]
df = df.drop(columns=drp2)
df.select_dtypes(exclude="number").columns
df.shape, df.head()

((21609, 12),
    Sale Price  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
 0    221900.0               3             1.00               1180.0
 1    538000.0               3             2.25               2570.0
 2    180000.0               2             1.00                770.0
 3    604000.0               4             3.00               1960.0
 4    510000.0               3             2.00               1680.0

    Lot Area (in Sqft)  No of Floors  Overall Grade  \
 0              5650.0           1.0              7
 1              7242.0           2.0              7
 2             10000.0           1.0              6
 3              5000.0           1.0              7
 4              8080.0           1.0              8

    Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
 0                                     1180.0                        0
 1                                     2170.0                      400
 2                                      770.0                        0
 3                                     1050.0                      910
 4                                     1680.0                        0

    Age of House (in Years)  Living Area after Renovation (in Sqft)  \
 0                       63                                  1340.0
 1                       67                                  1690.0
 2                       85                                  2720.0
 3                       53                                  1360.0
 4                       31                                  1800.0

    Lot Area after Renovation (in Sqft)
 0                                 5650
 1                                 7639
 2                                 8062
 3                                 5000
 4                                 7503  )

In [26]:
df.corr()

,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
Sale Price,1.000000,0.308463,0.525090,0.702056,0.089559,0.256941,0.580654,0.605366,0.323813,-0.054034,0.585394,0.082445
No of Bedrooms,0.308463,1.000000,0.515813,0.576628,0.031692,0.175536,0.349223,0.477549,0.303294,-0.154113,0.391771,0.029264
No of Bathrooms,0.525090,0.515813,1.000000,0.754568,0.087732,0.500776,0.635638,0.685088,0.283798,-0.505954,0.568568,0.087226
Flat Area (in Sqft),0.702056,0.576628,0.754568,1.000000,0.172721,0.354142,0.705725,0.876226,0.435142,-0.318146,0.756185,0.183223
Lot Area (in Sqft),0.089559,0.031692,0.087732,0.172721,1.000000,-0.005162,0.102314,0.183492,0.015252,-0.053119,0.144507,0.718527
No of Floors,0.256941,0.175536,0.500776,0.354142,-0.005162,1.000000,0.461368,0.524031,-0.245572,-0.489244,0.280106,-0.011204
Overall Grade,0.580654,0.349223,0.635638,0.705725,0.102314,0.461368,1.000000,0.705153,0.145232,-0.456711,0.681362,0.107581
Area of the House from Basement (in Sqft),0.605366,0.477549,0.685088,0.876226,0.183492,0.524031,0.705153,1.000000,-0.051825,-0.423848,0.731996,0.194106
Basement Area (in Sqft),0.323813,0.303294,0.283798,0.435142,0.015252,-0.245572,0.145232,-0.051825,1.000000,0.133072,0.200302,0.017263
Age of House (in Years),-0.054034,-0.154113,-0.505954,-0.318146,-0.053119,-0.489244,-0.456711,-0.423848,0.133072,1.000000,-0.326307,-0.071016
Living Area after Renovation (in Sqft),0.585394,0.391771,0.568568,0.756185,0.144507,0.280106,0.681362,0.731996,0.200302,-0.326307,1.000000,0.183188
Lot Area after Renovation (in Sqft),0.082445,0.029264,0.087226,0.183223,0.718527,-0.011204,0.107581,0.194106,0.017263,-0.071016,0.183188,1.000000

In [28]:
df.corr().iloc[0]

Sale Price                                   1.000000
No of Bedrooms                               0.308463
No of Bathrooms                              0.525090
Flat Area (in Sqft)                          0.702056
Lot Area (in Sqft)                           0.089559
No of Floors                                 0.256941
Overall Grade                                0.580654
Area of the House from Basement (in Sqft)    0.605366
Basement Area (in Sqft)                      0.323813
Age of House (in Years)                     -0.054034
Living Area after Renovation (in Sqft)       0.585394
Lot Area after Renovation (in Sqft)          0.082445
Name: Sale Price, dtype: float64

In [29]:
df.corr().iloc[3]

Sale Price                                   0.702056
No of Bedrooms                               0.576628
No of Bathrooms                              0.754568
Flat Area (in Sqft)                          1.000000
Lot Area (in Sqft)                           0.172721
No of Floors                                 0.354142
Overall Grade                                0.705725
Area of the House from Basement (in Sqft)    0.876226
Basement Area (in Sqft)                      0.435142
Age of House (in Years)                     -0.318146
Living Area after Renovation (in Sqft)       0.756185
Lot Area after Renovation (in Sqft)          0.183223
Name: Flat Area (in Sqft), dtype: float64

In [31]:
df.columns

Index(['Sale Price', 'No of Bedrooms', 'No of Bathrooms',
       'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors',
       'Overall Grade', 'Area of the House from Basement (in Sqft)',
       'Basement Area (in Sqft)', 'Age of House (in Years)',
       'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)'],
      dtype='object')

In [32]:
drp3 = [
    "No of Bedrooms",
    "Lot Area (in Sqft)",
    "No of Floors",
    "Area of the House from Basement (in Sqft)",
    "Basement Area (in Sqft)",
    "Living Area after Renovation (in Sqft)",
    'Lot Area after Renovation (in Sqft)'
]
df = df.drop(columns=drp3)
df.select_dtypes(exclude="number").columns
df.shape, df.head()

((21609, 5),
    Sale Price  No of Bathrooms  Flat Area (in Sqft)  Overall Grade  \
 0    221900.0             1.00               1180.0              7
 1    538000.0             2.25               2570.0              7
 2    180000.0             1.00                770.0              6
 3    604000.0             3.00               1960.0              7
 4    510000.0             2.00               1680.0              8

    Age of House (in Years)
 0                       63
 1                       67
 2                       85
 3                       53
 4                       31  )